### ISSUE TITLE
GitHub best practices

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#13]
@firasm, I understand that we must fork and branch for our group project as it is a collaborative environment, and it is best practice to not work directly on master.

Is it necessary to branch when working on our assignment repos? participation repos?

**Comment by firasm** [comment]
It's not **_necessary_** per se, but it's highly recommended as good practice.

The reason is so that you can pull upstream changes from the original repo without having to deal with merge conflicts when merging the changes in your forked master. 

I've quoted the relevant section from Happy Git with R here:

> If you make any commits in your local repository, I strongly recommend that you work in a new branch, not master.
> 
> I strongly recommend that you do not make commits to master of a repo you have forked.
> 
> This will make your life much easier if you want to pull upstream work into your copy. The OWNER of REPO will also be happier to receive your pull request from a non-master branch.
> 

More information [here](https://happygitwithr.com/fork-and-clone.html#dont-touch-master)

Hope this helps!

**Comment by firasm** [comment]
Hi @dy-lin is this solved? if yes, let's close the issue
