### ISSUE TITLE
Milestone 2- Task 2.4

### ISSUE THREAD

**Issue by Nima-Jamshidi** [STAT547-UBC-2019-20/Discussions#20]
Could you explain the first point of Task 2.4?

> - Be done in Rmarkdown and should not have any “hard-coded” (use r code chunks and inline r code) numbers and values

Does it mean that the Rmarkdown file should not include any r code chunks? Should we instead use R script to calculate numbers and values (eg. a table)? If yes, how can we integrate R scripts produced numbers and values in the Rmarkdown output?

Or does it mean that we ought to create a PDF or HTML file from R script using knit function?

**Comment by firasm** [comment]
Good question @Nima-Jamshidi !

Actually, this is an error. 

@STAT547-UBC-2019-20/students: this might be useful for you to know as well. 

I have removed that line, as well as the line that asks you to knit your file with a script milestone03 online with that change. Both those point belongs in Milestone03 as you will learn about it in cm106 on Thursday next week.

**Comment by dy-lin** [comment]
So what is it exactly that we have to do for Task 2.4? Just an Rmarkdown file knitted to PDF/HTML? (where we press knit in RStudio, instead of knitting in an Rscript?)

**Comment by firasm** [comment]
Yes, that’s it. Let’s just get it ready for automation next week.

**Comment by Nima-Jamshidi** [comment]
Thank you @firasm !

**Comment by evelynjulia** [comment]
And should the file be in the scripts folder or stay in Docs?

**Comment by firasm** [comment]
I’d put them in docs personally but one could make an argument that an Rmd file is also a script.

**Comment by dy-lin** [comment]
Just to clarify, so our milestone02 Rmarkdown file for Task 2.4, is using code chunks (like milestone01), which is completely unrelated to the scripts written for 2.1, 2.2 and 2.3?

**Comment by firasm** [comment]
@STAT547-UBC-2019-20/students: Update on milestone2 

**I have made it clearer online that Task 2.4 is now optional for this week.** 

--------------

To answer your question @dy-lin, I wouldn't say it's "completely" unrelated. 

Let's say your scripts are:

1. Load data
2. Clean/wrangle the data (load in the raw data you saved from script 1)
3. EDA to export some plots (loading in the cleaned/wrangled data from script2)

Your final report will be an Rmd file and you should use the plots you produced from script 3 above. 
You no longer need to include or reproduce the code chunks to produce the plots, just import in the images from the EDA Rmd you did in milestone1. 

Next week in milestone3, you will write one more script that knits your Rmd file into a final html/pdf report. The code chunks in your final report Rmd file may be useful if you want to do your linear regression within the final report Rmd file rather than as a separate script (but again, this is for next week).

**Comment by almas2019** [comment]
Hi @firasm , so just to confirm. Based on what I see on the milestone 2, only tasks 2.1-2.3 and task 3 are required. We don't need to a draft report this week(task 2.4)? Is this correct?

**Comment by firasm** [comment]
Correct!
