### ISSUE TITLE
dccGraph only accepts plotly?

### ISSUE THREAD

**Issue by mksm1228** [STAT547-UBC-2019-20/Discussions#49]
I am trying to complete task 2.5 using only ggplot but it seems like this is not possible? Is it true that dccGraph only "accepts" plotly graphs (which are just "enhanced" ggplot2 graphs) and not standard ggplot2 graphs?

**Comment by firasm** [comment]
Correct - you need to surround ggplot2 objects with "ggplotly()" in order for the plots to work in Dash. This is because ggplot graphs are not interactive by default. 

I think you might be mis-reading the instructions, you are meant to use ggplotly, I guess I laid it out as I did because they are "steps" to the final thing you need to arrive at.

**Comment by mksm1228** [comment]
Thanks @firasm for the clarification!
