### ISSUE TITLE
running code from terminal packages error

### ISSUE THREAD

**Issue by hanrach** [STAT547-UBC-2019-20/Discussions#52]
I'm getting an error when I call my script from the command line, and I did not get it before. I think this is happening after I updated my R. 
After running `make data/mydata.csv` it gives me `Error in library(docopt) : there is no package called ‘docopt’`.
Also happens for other packages too. I know for sure that these packages are installed, some how from the terminal it can't find it. How do I fix this?

**Comment by firasm** [comment]
There could be two problems:

1) you have multiple versions of R installed (in this case, delete the old one and things should fix). 

2) You may need to update where the terminal is looking for packages.

Here are some instructions (from Professor Tiffany Timbers) that may help:

-------------------------------------------
Make Rscript see the correct directory to load libraries:

1. Open RStudio and type `.libPaths()` in the **console**, you will probably see something like this:

```
> .libPaths()

[1] "C:/Users/ttimbers/Documents/R/win-library/3.4"
[2] "C:/Program Files/R/R-3.4.3/library"
```

2. in Terminal, type `cd` to make sure you are in your home directory

3. Save a file here called `.Renviron` that contains:
```
R_LIBS=PATH_TO_YOUR_FIRST_LIBRARY_IN_RSTUDIO
```
so, for example, mine would be:

```
R_LIBS=C:/Users/ttimbers/Documents/R/win-library/3.4
```

4. Quit Terminal

5. Re-open Terminal and see if your library paths now look like they do in the RStudio **console**:
```
Rscript -e ".libPaths()"
```

6. Now, try loading some library that you have installed through RStudio previously (e.g., `ezknitr`)

```
Rscript -e "library(IRkernel)"
```

*note - on Windows it is extremely important that you use " instead of ' after -e. You can use single quotes inside the double quotes if more are needed (e.g., `Rscript -e "print('hi')"`)

**Comment by hanrach** [comment]
After saving the .Renviron file, and loading libraries like `tidyverse`
`Rscript -e "library(tidyverse)`
I get the following error: 
```
Error: package or namespace load failed for ‘tidyverse’ in library.dynam(lib, package, package.lib):
 shared object ‘rlang.dylib’ not found
Execution halted
```
I think I only have one version of R installed because if I navigate to `/Library/Frameworks/R.framework/Versions/` there is only one version 3.6.

**Comment by hanrach** [comment]
Actually after using Terminal instead of iTerm2(mac terminal replacement), it's working. I'm not sure why. Thanks!
