### ISSUE TITLE
switch/toggle

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#57]
I'm looking for an 'on and off' toggle. or switch dash component, but can't seem to find one. I've tried using the checklist but it doesn't seem to work.

is there something else part of DashR that can be imported for this feature?

**Comment by yuliaUU** [comment]
[this one](https://dash.plotly.com/dash-daq/toggleswitch)?

you probably need to modify the syntax a bit, cause this one is for Python

**Comment by yuliaUU** [comment]
found for R , [here](https://dashr.plotly.com/dash-daq/toggleswitch)
but you will need extra library `library(dashDaq)`

**Comment by dy-lin** [comment]
Thank you! So much of the documentation is written for Python :(

**Comment by yuliaUU** [comment]
I know! I also struggle to find examples done in R:/

**Comment by firasm** [comment]
I think the issue here is that if you google things, the python version came "first" so all the search results are for it. R came more recently, but it is at feature-parity so all the same features are present.

One tip: if you find documentation for python at: https://dash.plotly.com, there is an equivalent website for at https://dashR.plotly.com (notice the R). 

So the DAQ for python is at: https://dash.plotly.com/dash-daq
Then the DAQ for R is at     : https://dashR.plotly.com/dash-daq

So protip: if you find documentation at dash.plotly, just replace dash with dashR and you should see the R equivalents!

**Comment by dy-lin** [comment]
Thanks! In case anyone else is looking into toggles, I actually ended up using a [`daqBooleanSwitch`](https://dashr.plotly.com/dash-daq/booleanswitch)!
