### ISSUE TITLE
radio item display

### ISSUE THREAD

**Issue by dy-lin** [STAT547-UBC-2019-20/Discussions#58]
my radio buttons seems to inline by default, despite not having the `labelStyle = list("display" = "inline-block")` enabled... did anyone else run into this problem, and know how to separate them each on one line?

**Comment by yuliaUU** [comment]
`app <- Dash$new(external_stylesheets = "https://codepen.io/chriddyp/pen/bWLwgP.css")`

The example they used in that website used external style. So I read the issue is because you need to apply that CSS style format

[Here is the link](https://community.plotly.com/t/display-checklist-radioitems-as-a-block/5065)

**Comment by firasm** [comment]
Did this fix your issue @dy-lin ?

if not please link to your app so I can try it!

**Comment by dy-lin** [comment]
Yes, it did! I'll close the issue. It is not very clear in the dashR documentation that a custom css file is used.
