### ISSUE TITLE
Assignment 5 Task 2

### ISSUE THREAD

**Issue by almas2019** [STAT547-UBC-2019-20/Discussions#62]
Hi all, 

I was wondering for task 2, do we have 2 other graphs that are connected by the slider (so a total of 3 graphs in the app.R) or is the first graph supposed to also be connected to the slider? Also can we change the plot we created for assignment 4 as my plot is not very amenable to the slider?

**Comment by yuliaUU** [comment]
No,
First graph connected to dropdown and a radial button for log scale

Other two graphs updates based on a slider

**Comment by almas2019** [comment]
Okay so 3 graphs in total, thank you!

**Comment by yuliaUU** [comment]
Yes! Correct!

**Comment by almas2019** [comment]
@yuliaUU for the slider I am just confused here. So if a value like Very Good is selected, should the graphs also include fair and good diamonds in a cumulative fashion? Or should it be like the dropdown, where only results from very good diamonds should show? I am confused on how to interpret a slider's value in the context of the graph?

**Comment by yuliaUU** [comment]
I updated instructions and provided some examples of what is needed [here](https://stat545.stat.ubc.ca/evaluation/assignment_05/assignment_05/)

**Comment by almas2019** [comment]
Hi @yuliaUU thank you for your reply. I took a look at the link, but it still does not seem to answer my question above about the slider. I was wondering if you could elaborate on that?

**Comment by yuliaUU** [comment]
@almas2019 (sorry was typing)
both options will work, I could not specify more because it will depend on the graphs you created

e.g. for example, if you plot price vs carat, then yes, input from the slider ( e.g.cut is Very Good) will  update the graph so that the relationship between price and carat only shown for diamonds with Very Good cut

However, you could already have a graph that has cut as one of the axis ( e.g. price vs cut).Then you have several options:
1. update the graph so that only the relationship between price and cut only for diamonds with Very Good cut is shown. not the best graph to produce, but it is  a possibility
2. make a slider that shows some different quality ( e.g color = D) and update your graph so that the price vs cut relationship is plotted  for diamonds with color "D"

**Comment by almas2019** [comment]
Okay thank you that makes sense!
