### ISSUE TITLE
Assignment 6 bug fixes

### ISSUE THREAD

**Issue by SaelinB** [STAT547-UBC-2019-20/Discussions#75]
Hi, 

I just wanted to double-check that there is a bug here, because I fixed the other bugs and the app runs fine with no error, both locally and on heroku:

app$run_server(host = "0.0.0.0", ports = Sys.getenv('PORT', 8050))

Thanks

**Comment by yuliaUU** [comment]
can you try changing to host='127.0.0.1'? will it work?

**Comment by SaelinB** [comment]
app$run_server(host = '127.0.0.1', ports = Sys.getenv('PORT', 8050)) 
app$run_server(host = '127.0.0.1')

Both work as well

**Comment by yuliaUU** [comment]
Awesome !lets then use one of those^^

**Comment by firasm** [comment]
I think you misunderstood @yuliaUU, I think @SaelinB is saying they're actually all working.

@SaelinB Not all bugs throw errors... compare what is in the app to this:

`app$run_server(host = '0.0.0.0', port = Sys.getenv('PORT', 8050))`

Hint: one of the arguments is not spelled correctly.

This is a tricky bug to find!

**Comment by yuliaUU** [comment]
@firasm  yes, it was part of the feedback I gave her:
her line: `app$run_server(host = '0.0.0.0', port = Sys.getenv('PORT', 8050))` won't work on my computer: because when I run the app, then the massage says in need to go to `http://0.0.0.0:8050 /` to see the app, so when I do it, nothing is displayed. However,  if I type in browser `http://127.0.0.1:8050/` it works, so I asked her to modify that line so it can be read on all computers
