### ISSUE TITLE
cm105 

### ISSUE THREAD

**Issue by mnybe1** [STAT547-UBC-2019-20/Discussions#84]
Hi, I'm just getting my participation repo sorted and for cm105 we are required to submit the cloned demo project and make file. 
I have the demo project in my cm105 participation folder, but on git hub you can't access it/actually click on it, and therefore also can't get a link to the makefile. 
Just wondering how we submit these?
Thanks!

**Comment by dy-lin** [comment]
I remember having the same issue because you technically have a GitHub repo within another GitHub repo (i.e. `git submodules`). If you remove the `.git` directory in the demo project folder you should be able to commit and push those files just as you would regular files.

If that doesn't work, I would download the demo project as a `.zip` and move that into the participation repository (just don't use the `git clone` method).

**Comment by firasm** [comment]
Hey what @dy-lin said above is correct!

**Comment by mnybe1** [comment]
Great, thanks @dy-lin & @firasm !
